fail_fast: true
default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
        - id: black
          stages: [ pre-commit ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff # Run the linter.
        stages: [ pre-commit ]

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
      -   id: mypy
          stages: [ pre-commit ]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
      - id: commitizen-branch
        stages: [ pre-push ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        stages: [ pre-push ]
        args: [-c=pyproject.toml]
        additional_dependencies: [ "bandit[toml]" ]
